//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VetClinicEntities : DbContext
    {
        public VetClinicEntities()
            : base("name=VetClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Журнал_посещений> Журнал_посещений { get; set; }
        public virtual DbSet<Использованы_медикаменты> Использованы_медикаменты { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Медикаменты> Медикаменты { get; set; }
        public virtual DbSet<Оказание_услуг> Оказание_услуг { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<Животные> Животные { get; set; }
        public virtual DbSet<Породы> Породы { get; set; }
    }
}
