//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Животные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Животные()
        {
            this.Журнал_посещений = new HashSet<Журнал_посещений>();
        }
    
        public int Код_животного { get; set; }
        public int Порода { get; set; }
        public string Кличка { get; set; }
        public int Владелец { get; set; }
        public string Пол { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Окрас { get; set; }
        public string Информация { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Породы Породы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал_посещений> Журнал_посещений { get; set; }
    }
}
