//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журнал_посещений
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Журнал_посещений()
        {
            this.Использованы_медикаменты = new HashSet<Использованы_медикаменты>();
            this.Оказание_услуг = new HashSet<Оказание_услуг>();
        }
    
        public int Код_номера_журнала { get; set; }
        public System.DateTime Дата { get; set; }
        public int Код_животного { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Использованы_медикаменты> Использованы_медикаменты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оказание_услуг> Оказание_услуг { get; set; }
        public virtual Животные Животные { get; set; }
    }
}
