//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Медикаменты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Медикаменты()
        {
            this.Использованы_медикаменты = new HashSet<Использованы_медикаменты>();
        }
    
        public int Код_медикамента { get; set; }
        public string Наименование { get; set; }
        public string Единицы_измерения { get; set; }
        public string Описание { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Использованы_медикаменты> Использованы_медикаменты { get; set; }
    }
}
