//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оказание_услуг
    {
        public int C__препарата { get; set; }
        public int C__журнала_посещения { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_услуги { get; set; }
        public string Диагноз { get; set; }
    
        public virtual Журнал_посещений Журнал_посещений { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
